### ISSUE TITLE
Enhance getFileContent method

### ISSUE THREAD

**Issue by peter279k** [iranianpep/darksky#16]
It looks like this package uses the `file_get_contents` to request the remote url, but I think we need to more options when doing HTTP request.

I recommend using the `curl_*` functions or [Guzzle](https://github.com/guzzle/guzzle) can solve this issue.

Once we use the HTTP library, we can get the complete response information. For example, the response HTTP status code, response header, response body and so on.

We can also change `getFileContent` method name to another method name.

How about naming `getResponse` method?

**Comment by iranianpep** [comment]
Hey @peter279k 

Guzzle is definitely a better option, however I initially chose `file_get_contents` because of simplicity. I had a plan to use Guzzle and give the developer an option to choose between it and the existing `file_get_contents` but didn't have the chance to implement it.

Cheers,

**Comment by peter279k** [comment]
@iranianpep, thank you for your reply.

I can help you to implement this feature.

Do you have any idea about implementing this?

I think we can implement another method named `getResponse`? Thanks.

**Comment by iranianpep** [comment]
@peter279k 

I was thinking to define a private property called `requestMethod` and it can be set in the constructor. And if it's not set, by default `Guzzle` is chosen. Something like [this](https://github.com/google/recaptcha/blob/master/src/ReCaptcha/ReCaptcha.php) and [this](https://github.com/google/recaptcha/tree/master/src/ReCaptcha/RequestMethod). For the simplicity it can be in the same file, or each request method can be a `class` in its own file and extend an `interface` or `abstract` class like [this](https://github.com/google/recaptcha/blob/master/src/ReCaptcha/RequestMethod.php). I think the main method should be named `submit` or `doRequest` instead of `getResponse`. Hope this is clear and thanks for it in advance. If you're not able to do it, I'll do it at some point. Once this is done, the readme also needs to be updated.

Cheers,
Ehsan

**Comment by iranianpep** [comment]
Addressed in [here](https://github.com/iranianpep/darksky/pull/18).
