### ISSUE TITLE
Setting 'LAT' and 'LONG'

### ISSUE THREAD

**Issue by stebogit** [iranianpep/darksky#6]
@iranianpep thanks for your work here.

I was wondering why you decided to require `LAT` and `LONG` in the constructor, since in my opinion they are relevant to the actual data request.
I personally need to perform several requests for different locations so I'd see more appropriate something like:
```php
$darksky = new Darksky('API_KEY');
$forecast = $darksky->forecast('LAT', 'LONG');
$historic = $darksky->timeMachine('UNIX_TIME', 'LAT', 'LONG');
```
which would allow to avoid to instantiate a new `Darksky` instance for each call.

What do you think?

P.S. BTW the docs have a typo in `$result = $darksky->forcast();`

**Comment by iranianpep** [comment]
Hey @stebogit 

That's a valid question. The reason was that the two main functions `forecast` and `timeMachine` need `LAT` and `LONG` then in my opinion the existence of `Darksky` mainly depends on `LAT` and `LONG`. That's why I included them as the required parameters for the `construct` function.

In your case, you can set the new `LAT` and `LONG` each time before calling `forecast` function (which is not ideal). The other option is that in the next release I can add `LAT` and `LONG` as optional parameters for the functions which overwrite the ones set in the construct.

I'll fix the typo in doc now. Thanks for spotting it!

Cheers,

**Comment by stebogit** [comment]
> the existence of Darksky mainly depends on `LAT` and `LONG`

Well that's true for the `API_KEY`, whereas the *request* does depend on `LAT` and `LONG`.

I solved it with simply
```php
$darksky = new Darksky('API_KEY', '', '');
```
So you might just to default `LAT`/`LONG` to empty string in the constructor and it would work elegantly both ways.

BTW I'd also change the type hint of `LAT` and `LONG` to `float` or remove it altogether, cause they are more often numbers and you don't really need them to be string (they will be converted anyway in `generateRequestUrl()`); or you could cast them in the setters, so anyway the user wouldn't need to do it:

```php
$forecast = $darksky->forecast((string)$lat, (string)$lng); // ugh! 😖 
```

**Comment by iranianpep** [comment]
I moved the `LAT` and `LNG` to the request functions in https://github.com/iranianpep/darksky/tree/v1.4

Cheers,

**Comment by stebogit** [comment]
Great! 👍
